---
- name: Download jenkins repo
  command: wget -O /etc/yum.repos.d/jenkins.repo http://pkg.jenkins-ci.org/redhat/jenkins.repo
 
- name: Import Jenkins CI key
  rpm_key:
       key: http://pkg.jenkins-ci.org/redhat/jenkins-ci.org.key
