---
- name: Download Jenkins Repo and rpm key
  #command: wget -O /etc/yum.repos.d/jenkins.repo https://pkg.jenkins.io/redhat-stable/jenkins.repo
  get_url:
    url: https://pkg.jenkins.io/redhat-stable/jenkins.repo
    dest: /etc/yum.repos.d/jenkins.repo
- name: Import Jenkins CI key
  rpm_key:
        key: https://pkg.jenkins.io/redhat-stable/jenkins.io.key
        state: present
